---
title: "Project"
author: "Jan Sifrer"
date: "5. 4. 2022"
output: html_document
runtime: shiny
---

```{r, include=FALSE, echo=FALSE}
# source("Shiny/shiny.r", encoding = "UTF-8")

#source("library.r", encoding="UTF-8")

library(shiny)
library(shinythemes)
library(readr)
library(dplyr)
library(stringr)
library(lme4)
library(knitr)
library(DT)

# Load data
trend_data <- read_csv("koef.csv",col_types = cols(Time = col_character()))
#trend_data <- read_csv(url("https://raw.githubusercontent.com/JanSifrer/GEN-I-4-Analiza-zamasenosti-omrezja/main/koef.csv"),col_types = cols(Time = col_character()))

# Define UI
ui <- fluidPage(theme = shinytheme("united"),
                titlePanel("Congested grids"),
                sidebarLayout(
                  sidebarPanel(
                    
                    # Select type of trend to plot
                    selectInput(inputId = "name2", label = strong("Name of Grid"),
                                choices = unique(trend_data$Name2)[order(unique(trend_data$Name2))],
                                selected = "Diele - Meeden 380 Black [DIR] [DE]"),
                    
                    selectInput(inputId = "time", label = strong("Hour"),
                                choices = unique(trend_data$Time),
                                selected = "00:00:00"),
                    
                    selectInput(inputId = "day", label = strong("Day of the week"),
                                choices = unique(trend_data$Day)[order(unique(trend_data$Day))],
                                selected = 1),
                    
                    numericInput(inputId = "AT", label = strong("PTDF for AT"),
                                 value = 0.58860, min = -1, max = 1, step = 0.00001),
                    
                    numericInput(inputId = "BE", label = strong("PTDF for BE"),
                                 value = 0.25637, min = -1, max = 1, step = 0.00001),
                    
                    numericInput(inputId = "DE", label = strong("PTDF for DE"),
                                 value = 0.58860, min = -1, max = 1, step = 0.00001),
                    
                    numericInput(inputId = "FR", label = strong("PTDF for FR"),
                                 value = 0.38150, min = -1, max = 1, step = 0.00001),
                    
                    numericInput(inputId = "NL", label = strong("PTDF for NL"),
                                 value = 0, min = -1, max = 1, step = 0.00001),
                    
                    numericInput(inputId = "ALBE", label = strong("PTDF for ALBE"),
                                 value = -0.30955, min = -1, max = 1, step = 0.00001),
                    
                    numericInput(inputId = "ALDE", label = strong("PTDF for ALDE"),
                                 value = 0, min = -1, max = 1, step = 0.00001),
                    
                    numericInput(inputId = "RAM", label = strong("RAM"),
                                 value = 1399, min = 0, max = 99999, step = 0.01),
                    
                    
                  ),
                  
                  # Output: Description, lineplot, and reference
                  mainPanel(
                    tableOutput("table"),
                    plotOutput(outputId = "lineplot", height = "300px"),
                    plotOutput(outputId = "lineplot1", height = "300px")
                  )
                )
)

# Define server function
server <- function(input, output) {
  
  # Create scatterplot object the plotOutput function is expecting
  hh2 <- lmer(c ~ AT + BE + DE + FR + NL + ALBE + ALDE + RAM + (1|Name2/Day) + (1|Name2/Time), data = trend_data)
  
  output$lineplot <- renderPlot({
    trend_data1 <- trend_data[trend_data$Name2==input$name2,]
    trend_data1 <- trend_data1[trend_data1$Time==input$time,]
    #print(trend_data1$c)
    hist(trend_data1$what, breaks=60)
  })
  
  output$lineplot1 <- renderPlot({
    trend_data1 <- trend_data[trend_data$Name2==input$name2,]
    trend_data1 <- trend_data1[trend_data1$Time==input$time,]
    #print(trend_data1$c)
    plot(density(trend_data1$what))
  })

  
  # Pull in description of trend
  output$table <-  renderTable({
    trend_data1 <- trend_data[trend_data$Name2==input$name2,]
    trend_data1 <- trend_data1[trend_data1$Time==input$time,]
    
    PTDF <- data.frame("Day"=input$day,"Name2"=input$name2, "Time"=input$time, "AT"=input$AT, "BE"=input$BE, "DE"=input$DE, "FR"=input$FR, "NL"=input$NL, "ALBE"=input$ALBE, "ALDE"=input$ALDE, "RAM"=input$RAM)
    print(trend_data1[c(11,12,13,15,26)])
    out <- tryCatch(
      {
        v = predict(hh2,PTDF)
      },
      error=function(cond) {
        return(0)
      }
    )
    interval <- c(out - 1.96*sigma(hh2), out + 1.96*sigma(hh2))
    if (out == 0){hh = data.frame("Change some parameters!" = out)}
    else{
      hh = data.frame("low boundary" = interval[1], "value" = out, "High boundary" = interval[2], "RAM" = input$RAM, "Difference" = input$RAM - out, "Probability" = (sum(trend_data1$congested))/dim(trend_data1)[1])}
  })
}
```

```{r, echo=FALSE}
# Create Shiny object
shinyApp(ui = ui, server = server)
#1+1
```
